[tool.poetry]
name = "my-app"
version = "0.1.0"
description = ""
authors = ["Janne Keskitalo <janne.keskitalo@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
art = "^6.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
